### ISSUE TITLE
Please update contact info on cj-overlay

### ISSUE THREAD

**Issue by mgorny** [junghans/cj-overlay#4]
Hi,

Since your `@gentoo.org` address seems to be no longer on Bugzilla, please update the contact info in repositories.xml to your current address. Preferably by submitting a PR to https://github.com/gentoo/api-gentoo-org. Thanks!

**Comment by junghans** [comment]
Fixed in gentoo/api-gentoo-org@0d44cce430324fbe1b038033270f92dbdc4488ed.
